
# POST http: //localhost:4200/user/register
# Content-Type:application/json

# {
#    "email"   : "testtest6789@test.com",
#    "password": "123dfgRRSS123",
#    "username": "testtest6789"
# }

###

# GET http://localhost:4200/user/test
# Content-Type: application/json

###

GET http://localhost:4200/editor/page?content=iPhone%2014%E3%80%82Pro
Content-Type: application/json

